Bugfix/relative paths
modelon-community/impact-client-js pull request #5
Opened 2021-04-09 07:02 UTC by jacobtaxen

This appends the impact base uri to the requests, which is required when Impact is installed with a relative path. Since the webapp does not have access to the env variable, it takes the uri from the browsers location and uses everything up to the /workspaces part of the url.

2021-04-09 07:34 UTC, efredriksson-modelon requested changes
Thanks for working on a fix for this 👑 

There are a few problems with the approach. It does not handle if the relative URL would contain `/workspaces` and `_isRunAsCustomization` does not have a corresponding fix.

I suggest some common method '_urlComposition' that returns both base url and if it is running with a customization url (to collect the URL checking logic in one place). It would check the URL for "workspaces" and "customizations" "from the right" using the length of all components.

2021-04-12 12:17 UTC, efredriksson-modelon requested changes
Awesome! 🧇 (just one question)

2021-04-12 12:17 UTC, efredriksson-modelon commented on src/index.js
> +    let customizedWorkspaceId = components[workspaceIndex + 3] === "customization"
Should it not be `+2`? If the URL is /workspaces/:workspaceID/customization then woskspace ID is +1 and "customization" is +2.

2021-04-12 13:22 UTC, modelon-magnus reviewed
From which URI are these web apps run? Wouldn't it be possible to call the API relative? A simple modification in _addApiPrefix should then be enough. Finding out the base dynamically seems brittle and raises some security concerns.

Why not just pass the base path?

2021-04-16 13:20 UTC, efredriksson-modelon requested changes

2021-04-16 13:20 UTC, efredriksson-modelon commented on src/index.js
> +export function createClient(workspaceId, impactUrl='') {
Please add some documentation for this argument.

2021-04-19 08:14 UTC, efredriksson-modelon approved these changes
👍

2021-04-19 09:04 UTC, modelon-magnus approved these changes
Much better than the magical url parsing. :green_apple:

2021-04-19 10:30 UTC, merged